---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: httpd-deployment
 labels:
  type: Webserver
spec:
 replicas: 3
 selector:
  matchLabels:
   type: Webserver
 template:
  metadata:
   name: httd-pod
   labels:
    type: webserver
  spec:
   containers: 
    - name: myhttpd
      image: httpd
      resources:
       requests:
        memory: "64Mi"
        cpu: "250m"
       limits:
         memory: "128Mi"
         cpu: "500m"
...
