---
apiVersion: v1
kind: Pod
metadata:
 name: tomcat-pod
 labels:
  type: appserver
spec:
 containers:
  - name: mytomcat
    image: tomee
 tolerations:
  - key: slave1
    value: intelliqit1
    operator: Equal
    effect: NoSchedule
...
